# Generated by Django 4.0.3 on 2022-08-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.city'),
        ),
    ]
