# Generated by Django 4.0.3 on 2022-08-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_destination_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
