# Generated by Django 4.0.3 on 2022-08-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
    ]
