# Generated by Django 4.0.3 on 2022-08-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_productorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_orders',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productorder'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
