# Generated by Django 4.0.3 on 2022-08-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_product_orders_productorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_orders',
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
