# Generated by Django 4.0.3 on 2022-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
